### ISSUE TITLE
$or Filter not working

### ISSUE THREAD

**Issue by danielerne** [pimcore/data-hub#178]
Filters are relying on the deprecated buildSQLCondition Helper Class from Pimcore.
The helper class (\Pimcore\Bundle\AdminBundle\Controller\Rest\Helper) has some issues with $or statement and when the name of the variable comes twice:
{"kw":{"$gt":0},"$or":[{"state":"finish", "state":"update_content"}]}
Results in:
((`kw` > '0') AND ((`state` = 'update_content') ) ) " 

The second state is ignored.
If we rename the second state to state_2:
"{"kw":{"$gt":0},"$or":[{"state":"finish","state_2":"update_content"}]}
Results in:
((`kw` > '0') AND ((`state` = 'finish') OR (`state_2` = 'update_content') ) )

It works. But it's not the expected result.

For further filtering with datahub an $or statement in filters or an $in is necessary.

**Comment by dvesh3** [comment]
@danielerne complete REST API is deprecated and will be removed in Pimcore 7. please see https://github.com/pimcore/pimcore/pull/5517 

about your issue, the problem is here: https://github.com/pimcore/pimcore/blob/efcb11acc1d646085b7d2c21c734a2acba4251fb/bundles/AdminBundle/Controller/Rest/AbstractRestController.php#L313
`json_decode` overwrites the duplicate keys provided in json condition.

@weisswurstkanone do you think we'll be able to support new structure for $or conditions like mentioned here https://restdb.io/docs/querying-with-the-api?

**Comment by weisswurstkanone** [comment]
It is deprecated but this doesn't mean that we can't provide the same logic, right ?

**Comment by dvesh3** [comment]
I'm just trying to make a point here that we need to support both existing and new structure.

**Comment by weisswurstkanone** [comment]
Exactly

**Comment by weisswurstkanone** [comment]
see #179 and #180

**Comment by weisswurstkanone** [comment]
Well, @dvesh3 is right but with a small change and a  bugfix which is integrated in #180 the following example is supposed to work (submitted the same fix for deprecated webservice in https://github.com/pimcore/pimcore/pull/6094)

q={"$or": [{"o_classname" : "Car"}, {"o_classname":"AccessoryPart"}]}

Difference is that $or is applied to a list of subconditions.
You should also be able to nest this stuff.

**Comment by danielerne** [comment]
Great! Thanks for this fast reply and bugfix
