### ISSUE TITLE
Document query type

### ISSUE THREAD

**Issue by weisswurstkanone** [pimcore/data-hub#49]
$document->getElement

**Comment by mrpdean** [comment]
Hi,

I've just started playing around with the Data Hub and so far I'm loving it.

Is this feature request referring to eventually being able to query documents and their content blocks via Graph QL?  Because that would be great.

Thanks.

**Comment by weisswurstkanone** [comment]
Excactly! It is not on the top-prio list, though. But please describe your actual usecase here and we will try to consider your input ;-) Many thanks!

**Comment by julmot** [comment]
My use case: I would like to be able to create a new document, create and manage bricks and publish and preview that document.

Potential easy solution approach: The document simply shows editables (must look more like native form elements) and clicking the preview button would show the "live" respectively the decoupled frontend application with the provided information. However, this would loose the ability to edit bricks context-sensitive, at the place where they are rendered.

Potential user friendly solution approach: Creating a document already opens/embeds the decoupled frontend, which would render all managed bricks. Pimcore provides a URL on a per-brick basis, that when calling it, renders editables (must look more like native form elements) and allows saving. The frontend can then e.g. implement an edit button on each brick that opens a modal where the iframe is embedded. This would allow context sensitive editing with previews directly after closing the modal and with a decoupled approach. The same principle would work in case no bricks were managed yet (edit button that opens an iframe to create a new brick instead of an iframe that manages an existing brick). For Pimcore it should be easy to implement and for decoupled frontends it allows to control the edit button UX.

What do you think? I'm happy to discuss this further, because I think this is a mandatory feature that users expect even when using Pimcore as data hub.

**Comment by solverat** [comment]
@julmot this is almost impossible to manage. It's not possible to use a decoupled brick by brick configuration since the tag id/name determination needs the full document structure at rendering time. You also need to consider the session based modification (until you hit the save button). We tried to implement something like graphejs (http://grapesjs.com/demo.html) the other day and yea... we gave up on this. 

I think the only reasonable thing what data-hub could do is to provide a JSON output of each document containing all available tags to allow to build your react/vue.js whatever frontend. But that's not really the idea behind graph ql, right? However, there are also plans to provide document2json output with our toolbox, but we're also wanted to wait to see if data-hub can help us with that.

**Comment by julmot** [comment]
@solverat But wouldn't it possible to refactor that part of the architecture? I don't know what it needs to be able to read and write all editables of a brick, but let's imagine it's the document ID, the brick name, the brick ID and the brick position. All of that could be part of the URL that would be embedded using the iframe. Or, if it really needs to have the document for editing a single brick inside of it, wouldn't it possible to render all of them, but only make the target brick visible?
Would you mind to shine some light into what Pimcore would need to be able to edit a brick without a corresponding document and what you mean exactly with `session based modification`?

Yes JSON output isn't really what makes GraphQL so strong. You only need to transfer what you need, can define your own structure that you want to handle frontend-side, you can join directly on relations and because of that the most important benefit from my point of view is you loose the pain between backend/frontend teams as backendlers only need to specify schemas and frontendlers can query data however and whereever they want.

**Comment by weisswurstkanone** [comment]
Further work will be covered by separate issues.
